[theme]
base = "dark"
primaryColor = "#FF6B6B"  # A brighter red for buttons/accents
backgroundColor = "#556285"  # Softer dark blue-gray (better contrast on mobile)
secondaryBackgroundColor = "#4A6295" # Sidebar/background sections
textColor = "#F0F3F4"  # Bright enough to show up clearly
font = "sans serif"
