[theme]
base = "dark"  # You can change to "light" if preferred
primaryColor = "#d44242"  # Bold red for buttons/accents
backgroundColor = "#1c1f26"  # Very dark navy-gray for body
secondaryBackgroundColor = "#2c3e50"  # Dark but lighter than main background (for sidebar, boxes)
textColor = "#F5F7FA"  # Very light gray for high contrast
font = "sans serif"
